import { Injectable, OnInit } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class OrderdetailsService {

  constructor() { }

  orderdetails = [
    {
      id:1,
      brandname:'Belle Chic',
      desc:'A beautiful long green dress on a hanger',
      price:2350,
      brandimg:'/assets/images/c1.jpg',
      fabric:'Cotton',
      Size:'[S,M,L,XL,XXL]',
      origin:'India',
    },
    {
      id:2,
      brandname:'Threads & Trends',
      desc:'Indian kashmiri kaftaan',
      price:900,
      brandimg:'/assets/images/c2.jpg',
      fabric:'Crepe',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:3,
      brandname:'Fashionista',
      desc:'A jacket for sale on a coat hanger',
      price:1200,
      brandimg:'/assets/images/c3.jpg',
      fabric:'Rayon',
      Size:'[S,M,L]',
      origin:'India',
    },
    
    {
      id:4,
      brandname:'Curves',
      desc:'Aerosmith sweater',
      price:850,
      brandimg:'/assets/images/c5.jpg',
      fabric:'Wool',
      Size:'[M,L,XL]',
      origin:'India',
    },
    {
      id:5,
      brandname:'Berrylush',
      desc:'Women Deep-V Neck Classic Bow Belt Vintage Casual Swing Dress',
      price:3000,
      brandimg:'/assets/images/C18.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:6,
      brandname:'Berrylush',
      desc:'Women Long Woolen Skirt Big Bottom',
      price:900,
      brandimg:'/assets/images/C19.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:7,
      brandname:'Berrylush',
      desc:'Tartan Waterfall Skirt',
      price:850,
      brandimg:'/assets/images/C20.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:8,
      brandname:'Berrylush',
      desc:'Women Vintage Sleeve Party Rockabilly Dress',
      price:850,
      brandimg:'/assets/images/C21.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:9,
      brandname:'Très Chic ',
      desc:'girl in blue summer floral dress',
      price:1500,
      brandimg:'/assets/images/c4.jpg',
      fabric:'Satin',
      Size:'[S,M]',
      origin:'India',
    },
    {
      id:10,
      brandname:'Aurelia',
      desc:'Stylish Women Crepe cream white Color Ethnic Motif Printed Kurti',
      price:900,
      brandimg:'/assets/images/c6.jpeg',
      fabric:'Cotton',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:11,
      brandname:'Berrylush',
      desc:'Casual American Crepe And Rasal',
      price:500,
      brandimg:'/assets/images/c7.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL]',
      origin:'India',

    },
    {
      id:12,
      brandname:'FashionEnsta',
      desc:'Women & Girls Wear Stretchable and Stylish Denim Jeans',
      price:700,
      brandimg:'/assets/images/c8.jpeg',
      fabric:'Denim',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:13,
      brandname:'Denim',
      desc:'Stylish Ravishing Women Jeans',
      price:1050,
      brandimg:'/assets/images/c9.jpeg',
      fabric:'Denim',
      Size:'[S,M,L,XL]',
      origin:'India',

    },
    {
      id:14,
      brandname:'Janasya',
      desc:'New Embroidery Gaithering kurti',
      price:850,
      brandimg:'/assets/images/c10.jpeg',
      fabric:'Cotton',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:15,
      brandname:'Westside',
      desc:'Trendy Retro Women Jeans',
      price:850,
      brandimg:'/assets/images/c11.png',
      fabric:'Cotton Blend',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:16,
      brandname:'Roadster',
      desc:'Arvi Creation Womens Cotton A-Line Kurti',
      price:850,
      brandimg:'/assets/images/c13.jpeg',
      fabric:'Satin',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:17,
      brandname:'Denim',
      desc:'Trendy Stylish light blue Denim Jeans For Women',
      price:850,
      brandimg:'/assets/images/c14.png',
      fabric:'Denim',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:18,
      brandname:'Denim',
      desc:'Stylish Womens  solid Denim Jeans',
      price:850,
      brandimg:'/assets/images/c15.png',
      fabric:'Denim',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:19,
      brandname:'Roadster',
      desc:'Fancy Modern women strechable jeans',
      price:850,
      brandimg:'/assets/images/c16.jpeg',
      fabric:'Cotton Blend',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:20,
      brandname:'Berrylush',
      desc:'FRONT SLIT Women Kurti',
      price:850,
      brandimg:'/assets/images/c17.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL]',
      origin:'India',
    },
    {
      id:21,
      brandname:'Berrylush',
      desc:'British Style New Winter Skirt',
      price:2000,
      brandimg:'/assets/images/C22.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:22,
      brandname:'Berrylush',
      desc:'Super Exotic Simple Skirt',
      price:700,
      brandimg:'/assets/images/c23.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:23,
      brandname:'Berrylush',
      desc:'Vintage New Fashion Dress',
      price:850,
      brandimg:'/assets/images/c24.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    },
    {
      id:24,
      brandname:'Berrylush',
      desc:'Women New Simple Cream White Skirt',
      price:850,
      brandimg:'/assets/images/c25.jpeg',
      fabric:'Rayon',
      Size:'[S,M,L,XL,XLL]',
      origin:'India',
    }
  ]
}
